packages:
  - packages/*
  - docs

catalogs:
  build:
    astro: ^5.14.1
  deps:
    astro-integration-kit: ^0.19.0
    c12: ^3.3.0
    dayjs: ^1.11.18
    defu: ^6.1.4
    jiti: ^2.6.0
    type-fest: ^5.0.1
    typescript: ^5.9.2
    unocss: ^66.5.2
    zx: ^8.8.4
  icons:
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/lucide': ^1.2.68
    '@iconify-json/uil': ^1.2.3
  lint:
    '@antfu/eslint-config': ^5.4.1
    '@unocss/eslint-plugin': ^66.5.2
    bumpp: ^10.2.3
    eslint: ^9.36.0
    eslint-plugin-astro: ^1.3.1
    husky: ^9.1.7
    lint-staged: ^16.2.1
    prettier-plugin-astro: ^0.14.1
    simple-git-hooks: ^2.13.1
  seo:
    '@vercel/og': ^0.8.5
    astro-seo: ^0.8.4

enablePrePostScripts: true

shamefullyHoist: true
